# Generated by Django 4.1.5 on 2023-01-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=100, verbose_name='Ответ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ans.category', verbose_name='Категория')),
            ],
        ),
    ]
